name: Part 1 CI workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: anexin/nodegoat:latest

  sast_scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Semgrep
        run: pip install semgrep
      - name: Run Semgrep and generate SARIF report
        run: semgrep scan --config=p/default --sarif --output=semgrep.sarif || true
      - name: Upload SARIF report to GitHub Security Alerts
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
      - name: Upload SARIF report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif-report
          path: semgrep.sarif

  sca_scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Snyk
        run: npm install -g snyk
      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk SCA Scan and generate SARIF report
        run: snyk test --sarif --output=snyk-results.sarif || true
      - name: Upload SARIF report to GitHub Security Alerts
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-results.sarif
      - name: Upload SARIF report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-sarif-report
          path: snyk-results.sarif
